sudo: false
dist: trusty
language: node_js

node_js:
  - '8'

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

branches:
  only:
    - master
    - /v\d+\.\d+[a-z]/

before_install:
  # Login to NPM registry
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

install:
  - npm ci

deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/travis-deploy.sh
    on:
      repo: dashevo/insight-ui
      tags: true
